BASE_FOLDER = '/home/marta/jku/activity_fair/'
DATASETS_FOLDER = '/home/marta/jku/activity_fair/datasets/'
FILTERED_DATASETS_FOLDER = '/home/marta/jku/activity_fair/datasets/filtered_datasets/'
FULL_DATASETS_FOLDER = '/home/marta/jku/activity_fair/datasets/full_datasets/'
SAMPLES_FOLDER = f'{FILTERED_DATASETS_FOLDER}/samples/'