learning_rate choice [1.e-2, 5.e-3, 1e-3]
embedding_size choice [8, 16, 32, 64, 128]
temperature choice [0.25, 0.5, 0.75, 1.] # The temperature parameter in the approx rank
beta choice [0.2, 0.4, 0.6, 0.8, 1.] # The regularization parameter between accuracy and fairness
