
# WARNING:
# 1. if you set inter_matrix_type='rating', you must set `unused_col: ~` in your data config files.
# 2. The dimensions of the last layer of users and items must be the same

# So grid search will not work since the last layer can vary between user and item
user_embedding_size choice [128, 256]
item_embedding_size choice [128, 256]
user_hidden_size_list choice [[16], [32], [64], [128]] # from the original paper on ml-100k
item_hidden_size_list choice [[16], [32], [64], [128]] # from the original paper on ml-100k
learning_rate choice [1.e-2, 5.e-3] #, 1e-3]
temperature choice [0.25, 0.5, 0.75, 1.]